export type Product={slug:string;name:string;nameAr:string;category:string;description:string;image:string;features:string[]};
export const products:Product[]=[
{slug:"drilling-buckets",name:"Drilling Buckets",nameAr:"بكيتات الحفر",category:"Foundation Tools",description:"Heavy-duty drilling buckets for piling, bored piles and demanding soil conditions.",image:"/products/bucket.png",features:["Custom diameters","Replaceable cutting teeth","Heavy-duty fabrication"]},
{slug:"rock-augers",name:"Rock Augers",nameAr:"أوجر حفر الصخور",category:"Augers",description:"High-torque augers engineered for rock, mixed ground and foundation drilling.",image:"/products/auger.png",features:["Rock cutting teeth","Custom connections","Multiple diameters"]},
{slug:"core-barrels",name:"Core Barrels",nameAr:"كور بارل",category:"Foundation Tools",description:"Robust core barrels for hard formations and large-diameter foundation drilling.",image:"/products/core.png",features:["Heavy wall construction","Custom diameter","Wear components"]},
{slug:"drilling-augers",name:"Drilling Augers",nameAr:"أوجر الحفر",category:"Augers",description:"Custom flight augers for professional piling and foundation contractors.",image:"/products/flight.png",features:["Custom flight pitch","Multiple cutting systems","Project-specific builds"]},
{slug:"kelly-accessories",name:"Kelly & Drilling Accessories",nameAr:"ملحقات الحفر وكيلي بار",category:"Accessories",description:"Adapters, drive components, pins, holders and fabricated drilling accessories.",image:"/products/accessories.png",features:["Custom fabrication","Replacement components","Contractor supply"]},
{slug:"custom-fabrication",name:"Custom Fabrication",nameAr:"تصنيع حسب الطلب",category:"Fabrication",description:"Made-to-order drilling tools and heavy steel components built to project requirements.",image:"/products/fabrication.jpg",features:["Drawing-based production","Heavy steel fabrication","Saudi project support"]}
];
export const company={name:"Advanced Fifth Axis",phone:"+966564707007",phoneDisplay:"056 470 7007",address:"Al Muftakira Street 4474, Jeddah Industrial, Saudi Arabia",vat:"310463296800003",cr:"4030336147"};